### ISSUE TITLE
fasl in the repo

### ISSUE THREAD

**Issue by informatimago** [ashok-khanna/autologger#1]
Don't commit fasl files!

You should delete it from the history (cf. eg. https://devconnected.com/how-to-delete-file-on-git/#Delete_Files_From_Git_History )

To avoid comiting object files, and others such spurious files, always commit in a `.gitignore` file pre-filled by common cruft, such as:  https://github.com/informatimago/lisp/blob/master/.gitignore

**Comment by ashok-khanna** [comment]
Awesome - thanks, have added `.gitignore`
