### ISSUE TITLE
vector-copy name

### ISSUE THREAD

**Issue by informatimago** [ashok-khanna/autologger#6]
https://github.com/ashok-khanna/autologger/blob/b2632c0ffec0d22afe755cc6e5afc816be28a2a9/cl-autologger.lisp#L325

Perhaps a better name would be `adjustable-vector-copy` or `copy-adjustable-vector`.
Otherwise we would wonder why not to use `copy-seq`.

**Comment by ashok-khanna** [comment]
Thanks, good idea. Renamed to `copy-adjustable-vector` to be consistent with `copy-seq` and will close this issue once published.

**Comment by ashok-khanna** [comment]
Done
